spring:
  application:
    name: order
server:
  port: 9202
logging:
  config: classpath:logback.xml
eureka:
  instance:
    #是否将自己的ip注册到eureka中，默认false 注册 主机名
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
