spring:
  application:
    name: eureka-server
server:
  port: 8761

eureka:
  instance:
    #注册实例名称
    hostname: localhost
    #是否将自己的ip注册到eureka中，默认false 注册 主机名
    prefer-ip-address: true
    # Eureka客户端需要多长时间发送心跳给Eureka，表明他仍然或者，默认是30
    # 通过下面方式我们可以设置，默认单位是秒
    lease-renewal-interval-in-seconds: 10
    # Eurkea服务器在接受到实例最后一次发送的心跳后，需要等待多久可以将次实例删除
    # 默认值是90
    # 通过下面方式我们可以设置，默认单位是秒
    lease-expiration-duration-in-seconds: 30
  client:
    #是否注册到eureka服务中
    register-with-eureka: false
    #是否拉取其他服务
    fetch-registry: false
    #server的访问地址
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  config: classpath:logback.xml
#management:
#  endpoints:
#    web:
#      exposure:
#        inclu
